new/urls.py
from django.urls import path

from . import views

app_name = 'new'
urlpatterns = [
    #path('loaddata/', views.load, name='load'),
    #path('metric/<int:data_id>/', views.metric, name='metric'),
    #path('mitigation', views.mitigate, name='mitigate'),
    #path('upload/', views.upload, name='upload'),
    #path('download/<path:filename>', views.download, name='download'),
    #path('clear/', views.cleardata, name='clear'),
    path('', views.index, name='index'),
    path('fVAE/', views.fVAE_data, name='fVAE'),
    path('fVAE/metric', views.fVAE_metric, name='fVAE_metric'),
    path('fVAE/mitigation', views.fVAE_miti, name='fVAE_miti'),
    path('fVAE/mitiresult', views.fVAE_miti_result, name='fVAE_result'),
    path('FFD/', views.FFD_data, name='FFD'),
    path('FFD/metric', views.FFD_metric, name='FFD_metric'),
    path('FFD/mitigation', views.FFD_mitigation, name='FFD_mitigation'),
    path('LfF/', views.LfF_data, name='LfF'),
    path('LfF/metric', views.LfF_metric, name='LfF_metric'),
    path('LfF/mitigation', views.LfF_mitigation, name='LfF_mitigation'),
    path('KDE/', views.KDE, name='KDE'),
    path('FB/', views.FB_data, name='FB'),
    path('FB/metric', views.FB_metric, name='FB_metric'),
    path('FB/mitigation', views.FB_mitigation, name='FB_mitigation'),
    path('CPR/', views.CPR_data, name='CPR'),
    path('CPR/metric', views.CPR_metric, name='CPR_metric'),
    path('CPR/mitigation', views.CPR_mitigation, name='CPR_mitigation'),
]

text/urls.py
from django.urls import path

from . import views

app_name = 'text'
urlpatterns = [
    path('loaddata/', views.load, name='load'),
    path('metric/<int:data_id>/', views.metric, name='metric'),
    path('mitigation', views.mitigate, name='mitigate'),
    path('upload/', views.upload, name='upload'),
    #path('download/<path:filename>', views.download, name='download'),
    #path('clear/', views.cleardata, name='clear'),
    path('', views.index, name='index'),
]

text/models.py
from django.db import models
import os

# Create your models here.
class Data(models.Model):
	datafile = models.FileField(upload_to='text/data/')
	config_data_json = models.CharField(max_length=1000, null=True)
	config_load_json = models.CharField(max_length=1000, null=True)
	datatype = models.CharField(max_length=10, default='text')

	aif_input_file_path = models.FilePathField(path='text/data/dataframes', null=True)
	
	def __str__(self):
		return os.path.basename(self.datafile.name)

text/forms.py
from django import forms


class DataForm(forms.Form):
	file = forms.FileField(label='파일을 선택하세요.')

text/views.py
import os
import mimetypes
import numpy as np
from glob import glob
import json

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from django.urls import reverse

#from aif360.datasets import AdultDataset
from aif360.metrics import utils
from Kaif.Metric import DataMetric
from sklearn.manifold import TSNE

from .forms import DataForm
from .models import Data
from .analyze import Kaifdata, KaifMitigation 

# Create your views here.

def index(request):
	datas = Data.objects.all()
	form = DataForm()
	return render(request, 'text/index.html', {'data_list':datas, 'form':form})


def upload(request):
	if request.method == 'POST':
		form = DataForm(request.POST, request.FILES)

		if form.is_valid():
			data = Data(datafile=request.FILES['file'])
			data.config_data_json = request.POST['config_data']
			data.save()

		return redirect(reverse('text:index'))
	
	else:
		form = ()
		files = glob('./' + request.path.split('/')[1] + '/data/*')

		return render(request, 'text/index.html', {'dl': files, 'form':form})


def load(request):
	if request.method == 'POST':
		items = list(request.POST.lists())
		data_index = request.POST.getlist('index')
		config_json = request.POST['config_load']
		datatype = request.path.split('/')[1]

		# data update
		for idx in data_index:
			d = Data.objects.get(id=idx)
			d.config_load_json = config_json
			d.datatype = datatype
			d.save()
		
		data = Kaifdata(data_index, datatype)  # Data loader

		num_classes = len(np.unique(data.aif_data.labels))
		dirichlet_alpha = 1.0 / num_classes
		intersect_groups = np.unique(data.aif_data.protected_attributes, axis=0)
		num_intersects = len(intersect_groups)

		## T-SNE
		model = TSNE(n_components=2)

		# Privileged dataset
		priv_index = np.where(data.aif_data.protected_attributes == data.aif_data.privileged_protected_attributes)[0]
		priv_dset = data.aif_data.subset(priv_index)

		# Unprivileged dataset
		unpriv_index = np.where(data.aif_data.protected_attributes == data.aif_data.unprivileged_protected_attributes)[0]
		unpriv_dset = data.aif_data.subset(unpriv_index)

		## T-SNE modeling
		tsne_data_priv = model.fit_transform(priv_dset.features)
		tsne_data_unpriv = model.fit_transform(unpriv_dset.features)

		data_info = {
			'num_classes': num_classes,
			'num_intersects': num_intersects,
			'intersect_groups': intersect_groups,
			'protected_attribute': data.aif_data.protected_attribute_names[0],
			'privileged_tsne_data': tsne_data_priv.tolist(),
			'unprivileged_tsne_data': tsne_data_unpriv.tolist()
		}

		context = {'info': data_info, 'data_id': idx}

		return render(request, 'text/data.html', context)

	return HttpResponse('You entered this page with not porper root.\nPlease return to index page.')


def metric(request, data_id):
	data = Data.objects.get(id=data_id)

	# re-load data
	data = Kaifdata([data.id], data.datatype)

	#lconfig = json.loads(data.config_load_json)
	privilege_group = [{'bias': 1}]
	unprivilege_group = [{'bias': 0}]

	metric = DataMetric(dataset=data.aif_data, privilege=privilege_group, unprivilege=unprivilege_group)

	context = {
		'num_positive_list': [metric.num_positive(), metric.num_positive(privileged=True), metric.num_positive(privileged=False)],
		'num_negative_list': [metric.num_negative(), metric.num_negative(privileged=True), metric.num_negative(privileged=False)],
		'base_rate_list': [metric.base_rate(), metric.base_rate(privileged=True), metric.base_rate(privileged=False)],
		'disparate_impact': metric.disparate_impact(),
		'statistical_parity_difference': metric.statistical_parity_difference(),
		'data': data,
		'd_id': data_id
	}

	return render(request, 'text/metric.html', context)


def mitigate(request):
	d_id = request.GET['d_id']
	m_id = request.GET['m_id']

	result = KaifMitigation(d_id, m_id)

	context = {
		'odm': result.data_metric_orig_obj,
		'ocm': result.class_metric_orig_obj,
		'tdm': result.data_metric_transf_obj,
		'tcm': result.class_metric_transf_obj
	}

	return render(request, 'text/mitigate.html', context)

templates/text/data.html
{% extends "data_base.html" %}

{% block metricReverse %}
<a href='{% url "text:metric" data_id %}'>Metric</a>
{% endblock metricReverse %}

templates/text/index.html
{% extends "index_base.html" %}

{% block title %}
<title>Raw</title>
{% endblock title %}

{% block data_preset %}
<form action="{% url 'text:upload' %}" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{{ message }}
	<p>{{ form.non_field_erros }}</p>
	<p>{{ form.file.label_tag }}</p>
	<p>
		{{ form.file.errors }}
		{{ form.file }}
	</p>
	<label for="config_data">Configure:</label>
	<textarea id="config_data" name="config_data" rows="10" cols="150">
{
	"sep" : "\t",
	"header" : 0,
	"names" : null
}	
	</textarea>
	<p><input type="submit" name="Upload"></p>
</form>
{% endblock data_preset %}

{% block load_preset %}
<form action='{% url "text:load" %}' method='post' enctype="multipart/form-data">
	{% csrf_token %}
	{% if data_list %}
		<h3>Data selection</h3>
			{% for f in data_list %}
				{% if f.aif_input_file_path %}
					<input type="checkbox" id={{f.id}} name=index value="{{f.id}}">
					<label for=index>(Analyzed) {{ f.datafile.name }}</label><br>
				{% else %}
					<input type="checkbox" id={{f.id}} name=index value="{{f.id}}">
					<label for=index>{{ f.datafile.name }}</label><br>
				{% endif %}
			{% endfor %}
		<h3>Required options</h3>
		<p>NOTE: These options will be read as JSON form.</p>
		<label for="config_load">Configure:</label>
		<textarea id="config_load" name="config_load" rows="15" cols="150">
{
	"document_column": "document",
	"label_column": "label",
	"privilege_keys": ["남자", "남성"],
	"unprivilege_keys": ["여자", "여성"],
	"favorable_classes": [1],
	"na_values": ["?"]
}
		</textarea><br>
    {% else %}
	    <p>No files.</p>
    {% endif %}
	<p><input type='submit' value='Load'/></p>
</form>
{% endblock load_preset %}

templates/text/metric.html
{% extends "metric_base.html" %}

{% block mitigationReverse %}
<p>
	<h2>Preprocessing</h2>
	<ul>
		<li><a href='{% url "text:mitigate" %}?d_id={{d_id}}&m_id=1'>Reweighing</a></li>
		<li><a href='{% url "text:mitigate" %}?d_id={{d_id}}&m_id=2'>Disperate Impact Remover</a></li>
		<li><a href='{% url "text:mitigate" %}?d_id={{d_id}}&m_id=3'>Learning Fair Representation</a></li>
	</ul>
</p>
<p>
	<h2>Inprocessing</h2>
	<ul>
		<li><a href='{% url "text:mitigate" %}?d_id={{d_id}}&m_id=4'>Adversarial Debiasing</a></li>
		<li><a href='{% url "text:mitigate" %}?d_id={{d_id}}&m_id=5'>Garry Fair Classifier</a></li>
		<li><a href='{% url "text:mitigate" %}?d_id={{d_id}}&m_id=6'>Meta Fair Classifier</a></li>
		<li><a href='{% url "text:mitigate" %}?d_id={{d_id}}&m_id=7'>Prejudice Remover</a></li>
	</ul>
</p>
<p>
	<h2>Postprocessing</h2>
	<ul>
		<li><a href='{% url "text:mitigate" %}?d_id={{d_id}}&m_id=8'>Calibrated Equalized Odds</a></li>
		<li><a href='{% url "text:mitigate" %}?d_id={{d_id}}&m_id=9'>Equalized Odds</a></li>
		<li><a href='{% url "text:mitigate" %}?d_id={{d_id}}&m_id=10'>Reject Option</a></li>
	</ul>
</p>
{% endblock mitigationReverse %}

templates/text/mitigate.html
{% extends "mitigate_base.html" %}