new/urls.py
from django.urls import path

from . import views

app_name = 'new'
urlpatterns = [
    #path('loaddata/', views.load, name='load'),
    #path('metric/<int:data_id>/', views.metric, name='metric'),
    #path('mitigation', views.mitigate, name='mitigate'),
    #path('upload/', views.upload, name='upload'),
    #path('download/<path:filename>', views.download, name='download'),
    #path('clear/', views.cleardata, name='clear'),
    path('', views.index, name='index'),
    path('fVAE/', views.fVAE_data, name='fVAE'),
    path('fVAE/metric', views.fVAE_metric, name='fVAE_metric'),
    path('fVAE/mitigation', views.fVAE_miti, name='fVAE_miti'),
    path('fVAE/mitiresult', views.fVAE_miti_result, name='fVAE_result'),
    path('FFD/', views.FFD_data, name='FFD'),
    path('FFD/metric', views.FFD_metric, name='FFD_metric'),
    path('FFD/mitigation', views.FFD_mitigation, name='FFD_mitigation'),
    path('LfF/', views.LfF_data, name='LfF'),
    path('LfF/metric', views.LfF_metric, name='LfF_metric'),
    path('LfF/mitigation', views.LfF_mitigation, name='LfF_mitigation'),
    path('KDE/', views.KDE, name='KDE'),
    path('FB/', views.FB_data, name='FB'),
    path('FB/metric', views.FB_metric, name='FB_metric'),
    path('FB/mitigation', views.FB_mitigation, name='FB_mitigation'),
    path('CPR/', views.CPR_data, name='CPR'),
    path('CPR/metric', views.CPR_metric, name='CPR_metric'),
    path('CPR/mitigation', views.CPR_mitigation, name='CPR_mitigation'),
]

new/models.py
from django.db import models

# Create your models here.

new/views.py
import pandas as pd
import numpy as np

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

from sklearn.manifold import TSNE
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import MinMaxScaler
import tensorflow.compat.v1 as tf

from Kaif.DataSet import aifData
from Kaif.Metric import DataMetric, ClassificationMetric

from FairnessVAE.solver_40dim_clatent import Solver

from celery.result import AsyncResult
from .tasks import get_fVAE_result

# Create your views here.

def index(request):
	return render(request, "new/index.html")


def fVAE_data(request):
	# CelebA dataset
	# Target class: heavy makeup
	# Protected attribute: male/female
	df = pd.read_table('./data/CelebA/list_attr_celeba.csv', sep=',')
	aif_data = aifData(
		df=df,
		label_name='Heavy_Makeup',
		favorable_classes=[1],
		protected_attribute_names=['Male'],
		privileged_classes=[[-1]],
		features_to_keep=['Heavy_Makeup', 'Male'],
		na_values=['?']
		)

	num_classes = len(np.unique(aif_data.labels))
	dirichlet_alpha = 1.0 / num_classes
	intersect_groups = np.unique(aif_data.protected_attributes, axis=0)
	num_intersects = len(intersect_groups)

	## T-SNE
	model = TSNE(n_components=2)

	# Privileged dataset
	priv_index = np.where(aif_data.protected_attributes == aif_data.privileged_protected_attributes)[0]
	priv_dset = aif_data.subset(priv_index)

	# Unprivileged dataset
	unpriv_index = np.where(aif_data.protected_attributes == aif_data.unprivileged_protected_attributes)[0]
	unpriv_dset = aif_data.subset(unpriv_index)

	## T-SNE modeling
	tsne_data_priv = model.fit_transform(priv_dset.features)
	tsne_data_unpriv = model.fit_transform(unpriv_dset.features)

	data_info = {
		'num_classes': num_classes,
		'num_intersects': num_intersects,
		'intersect_groups': intersect_groups,
		'protected_attribute': aif_data.protected_attribute_names[0],
		'privileged_tsne_data': tsne_data_priv.tolist(),
		'unprivileged_tsne_data': tsne_data_unpriv.tolist()
	}

	context = {'info': data_info, 'algorithm': 'fVAE'}

	return render(request, 'new/data.html', context)


def fVAE_metric(request):
	df = pd.read_table('./data/CelebA/list_attr_celeba.csv', sep=',')
	aif_data = aifData(
		df=df,
		label_name='Heavy_Makeup',
		favorable_classes=[1],
		protected_attribute_names=['Male'],
		privileged_classes=[[-1]],
		features_to_keep=['Heavy_Makeup', 'Male'],
		na_values=['?']
		)

	metric = DataMetric(dataset=aif_data, privilege=[{'Male':-1}], unprivilege=[{'Male':1}])

	context = {
		'num_positive_list': [metric.num_positive(), metric.num_positive(privileged=True), metric.num_positive(privileged=False)],
		'num_negative_list': [metric.num_negative(), metric.num_negative(privileged=True), metric.num_negative(privileged=False)],
		'base_rate_list': [metric.base_rate(), metric.base_rate(privileged=True), metric.base_rate(privileged=False)],
		'disparate_impact': metric.disparate_impact(),
		'statistical_parity_difference': metric.statistical_parity_difference(),
		'data': aif_data,
		'id': 0,
		'algorithm': 'fVAE'
	}

	return render(request, 'new/metric.html', context)


def fVAE_miti(request):
	result = get_fVAE_result.delay()

	url = f'mitiresult?id={result.id}'

	return HttpResponseRedirect(url)


def fVAE_miti_result(request):
	try:
		result = AsyncResult(request.GET['id'])
	except:
		return HttpResponse('You entered this page wrong route.<br>Please start from index page.<br><br><a href="new/index">go to index</a>')

	if result.ready():
		r = result.get()
	else:
		r = None

	context = {'id': result.id, 'result': r, 'algorithm': 'fVAE'}

	return render(request, 'new/mitigate.html', context)


def FFD_data(request):
	df = pd.read_csv('./new/FFD_miti_result.csv')
	# label: 0 (age < 20), 1 (20 < age < 40), 2 (age > 40)
	# protected: 0 (White), 1 (Black), 2 (Asian), 3 (Indian), 4 (Others)
	aif_data = aifData(
		df=df,
		label_name='base_label',
		favorable_classes=[1],
		protected_attribute_names=['base_protected'],
		privileged_classes=[[0]],
		)

	num_classes = len(np.unique(aif_data.labels))
	dirichlet_alpha = 1.0 / num_classes
	intersect_groups = np.unique(aif_data.protected_attributes, axis=0)
	num_intersects = len(intersect_groups)

	## T-SNE
	model = TSNE(n_components=2)

	# Privileged dataset
	priv_index = np.where(aif_data.protected_attributes == aif_data.privileged_protected_attributes)[0]
	priv_dset = aif_data.subset(priv_index)

	# Unprivileged dataset
	unpriv_index = np.where(aif_data.protected_attributes == aif_data.unprivileged_protected_attributes)[0]
	unpriv_dset = aif_data.subset(unpriv_index)

	## T-SNE modeling
	tsne_data_priv = model.fit_transform(priv_dset.features)
	tsne_data_unpriv = model.fit_transform(unpriv_dset.features)

	data_info = {
		'num_classes': num_classes,
		'num_intersects': num_intersects,
		'intersect_groups': intersect_groups,
		'protected_attribute': aif_data.protected_attribute_names[0],
		'privileged_tsne_data': tsne_data_priv.tolist(),
		'unprivileged_tsne_data': tsne_data_unpriv.tolist()
	}

	context = {'info': data_info, 'algorithm': 'FFD'}

	return render(request, 'new/data.html', context)


def FFD_metric(request):
	df = pd.read_csv('./new/FFD_miti_result.csv')
	# label: 0 (age < 20), 1 (20 < age < 40), 2 (age > 40)
	# protected: 0 (White), 1 (Black), 2 (Asian), 3 (Indian), 4 (Others)
	aif_data = aifData(
		df=df,
		label_name='base_label',
		favorable_classes=[1],
		protected_attribute_names=['base_protected'],
		privileged_classes=[[0]],
		)

	metric = DataMetric(dataset=aif_data, privilege=[{'base_protected':0}], unprivilege=[{'base_protected':1}, {'base_protected':2}, {'base_protected':3}])

	context = {
		'num_positive_list': [metric.num_positive(), metric.num_positive(privileged=True), metric.num_positive(privileged=False)],
		'num_negative_list': [metric.num_negative(), metric.num_negative(privileged=True), metric.num_negative(privileged=False)],
		'base_rate_list': [metric.base_rate(), metric.base_rate(privileged=True), metric.base_rate(privileged=False)],
		'disparate_impact': metric.disparate_impact(),
		'statistical_parity_difference': metric.statistical_parity_difference(),
		'data': aif_data,
		'id': 0,
		'algorithm': 'FFD'
	}

	return render(request, 'new/metric.html', context)



def FFD_mitigation(request):
	df = pd.read_csv('./new/FFD_miti_result.csv')
	# label: 0 (age < 20), 1 (20 < age < 40), 2 (age > 40)
	# protected: 0 (White), 1 (Black), 2 (Asian), 3 (Indian), 4 (Others)
	aif_data = aifData(
		df=df,
		label_name='base_label',
		favorable_classes=[1],
		protected_attribute_names=['base_protected'],
		privileged_classes=[[0]],
		)

	data_metric_orig = DataMetric(dataset=aif_data, privilege=[{'base_protected':0}], unprivilege=[{'base_protected':1}, {'base_protected':2}, {'base_protected':3}])
	data_metric_transf = DataMetric(dataset=aif_data, privilege=[{'base_protected':0}], unprivilege=[{'base_protected':1}, {'base_protected':2}, {'base_protected':3}])

	data_metric_orig_obj = {
		'num_positive': data_metric_orig.num_positive(),
		'num_negative': data_metric_orig.num_negative(),
		'base_rate': data_metric_orig.base_rate(),
		'disparate_impact': data_metric_orig.disparate_impact(),
		'statistical_parity_difference': data_metric_orig.statistical_parity_difference()
	}

	data_metric_transf_obj = {
		'num_positive': data_metric_transf.num_positive(),
		'num_negative': data_metric_transf.num_negative(),
		'base_rate': data_metric_transf.base_rate(),
		'disparate_impact': data_metric_transf.disparate_impact(),
		'statistical_parity_difference': data_metric_transf.statistical_parity_difference()
	}


	class_metric_orig = ClassificationMetric(
		dataset=aif_data,
		privilege=[{'base_protected':0}],
		unprivilege=[{'base_protected':1}, {'base_protected':2}, {'base_protected':3}],
		prediction_vector=df['base_prediction'].to_numpy(),
		target_label_name='base_label'
	)

	class_metric_orig_obj = {
		'performance': class_metric_orig.performance_measures(),
		'error_rate': class_metric_orig.error_rate(),
		'average_odds_difference': class_metric_orig.average_odds_difference(),
		'average_abs_odds_difference': class_metric_orig.average_abs_odds_difference(),
		'selection_rate': class_metric_orig.selection_rate(),
		'equal_opportunity_difference': class_metric_orig.equal_opportunity_difference(),
		'disparate_impact': class_metric_orig.disparate_impact(),
		'statistical_parity_difference': class_metric_orig.statistical_parity_difference(),
		'generalized_entropy_index': class_metric_orig.generalized_entropy_index(),
		'theil_index': class_metric_orig.theil_index()
	}

	transf_aif_data = aifData(
		df=df,
		label_name='debias_label',
		favorable_classes=[1],
		protected_attribute_names=['debias_protected'],
		privileged_classes=[[0]]
		)

	class_metric_transf = ClassificationMetric(
		dataset=transf_aif_data,
		privilege=[{'debias_protected':0}],
		unprivilege=[{'debias_protected':1}, {'debias_protected':2}, {'debias_protected':3}],
		prediction_vector=df['debias_prediction'].to_numpy(),
		target_label_name='base_label'
		)

	class_metric_transf_obj = {
		'performance': class_metric_transf.performance_measures(),
		'error_rate': class_metric_transf.error_rate(),
		'average_odds_difference': class_metric_transf.average_odds_difference(),
		'average_abs_odds_difference': class_metric_transf.average_abs_odds_difference(),
		'selection_rate': class_metric_transf.selection_rate(),
		'equal_opportunity_difference': class_metric_transf.equal_opportunity_difference(),
		'disparate_impact': class_metric_transf.disparate_impact(),
		'statistical_parity_difference': class_metric_transf.statistical_parity_difference(),
		'generalized_entropy_index': class_metric_transf.generalized_entropy_index(),
		'theil_index': class_metric_transf.theil_index()
	}

	result = {
		'odm': data_metric_orig_obj,
		'tdm': data_metric_transf_obj,
		'ocm': class_metric_orig_obj,
		'tcm': class_metric_transf_obj
	}

	context = {'id': '(null)', 'result': result, 'algorithm': 'FFD'}

templates/new/data.html
{% extends "data_base.html" %}

{% block metricReverse %}
<a href="/new/{{algorithm}}/metric">Metric</a>
{% endblock metricReverse %}

templates/new/index.html
{% extends "index_base.html" %}

{% block title %}
<title>New algorithms</title>
{% endblock title %}

{% block data_preset %}
<p>
<a href="{% url 'new:fVAE' %}">Fairness VAE</a>
<br>
<a href="{% url 'new:FFD' %}">Fair Feature Distillation</a>
<br>
<a href="{% url 'new:LfF' %}">Learning from Failure</a>
<br>
<a href="{% url 'new:KDE' %}">Kernel Density Estimation</a>
<br>
<a href="{% url 'new:FB' %}">Fair Batch</a>
<br>
<a href="{% url 'new:CPR' %}">Classifier-Projection Regularization</a>
</p>
{% endblock data_preset %}

templates/new/metric.html
{% extends "metric_base.html" %}

{% block mitigationReverse %}
<a href="/new/{{algorithm}}/mitigation">Mitigation</a>
{% endblock mitigationReverse %}

templates/new/mitigate.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Mitigation result</title>
	<link rel="stylesheet" href="{% static 'style/biaschart.css' %}">
	<link rel="stylesheet" href="{% static 'style/dlchart.css' %}">
</head>
<body>

	<h1>Mitigation</h1>

	{% if id %}
	<p>ID : {{id}}</p>
	{% else %}
	<p>No Queue</p>
	{% endif %}

	{% if result %}
		<h2>Original data metrics</h2>
		<p>Number of positives: {{result.odm.num_positive}}</p>
		<p>Number of negatives: {{result.odm.num_negative}}</p>
		<p>Base rate: {{result.odm.base_rate}}</p>
		<p>Disparate impact: {{result.odm.disparate_impact}}</p>
		<p>Statistical parity difference: {{result.odm.statistical_parity_difference}}</p>

		<h2>Transformed data metrics</h2>
		<p>Number of positives: {{result.tdm.num_positive}}</p>
		<p>Number of negatives: {{result.tdm.num_negative}}</p>
		<p>Base rate: {{result.tdm.base_rate}}</p>
		<p>Disparate impact: {{result.tdm.disparate_impact}}</p>
		<p>Statistical parity difference: {{result.tdm.statistical_parity_difference}}</p>

		<h2>Original classification metrics</h2>
		<p>Error rate: {{result.ocm.error_rate}}</p>
		<p>Average odds difference: {{result.ocm.average_odds_difference}}</p>
		<p>Average absolute odds difference: {{result.ocm.average_abs_odds_difference}}</p>
		<p>Selection rate: {{result.ocm.selection_rate}}</p>
		<p>Disparate impact: {{result.ocm.disparate_impact}}</p>
		<p>Statistical parity difference: {{result.ocm.statistical_parity_difference}}</p>
		<p>Generalized entropy index: {{result.ocm.generalized_entropy_index}}</p>
		<p>Theil index: {{result.ocm.theil_index}}</p>

		<h2>Transformed classification metrics</h2>
		<p>Error rate: {{result.tcm.error_rate}}</p>
		<p>Average odds difference: {{result.tcm.average_odds_difference}}</p>
		<p>Average absolute odds difference: {{result.tcm.average_abs_odds_difference}}</p>
		<p>Selection rate: {{result.tcm.selection_rate}}</p>
		<p>Disparate impact: {{result.tcm.disparate_impact}}</p>
		<p>Statistical parity difference: {{result.tcm.statistical_parity_difference}}</p>
		<p>Generalized entropy index: {{result.tcm.generalized_entropy_index}}</p>
		<p>Theil index: {{result.tcm.theil_index}}</p>

	<!-- Bias Chart Area -->
		<figure class="highcharts-figure">
			<div id="bar_container" class="bar"></div>
			<div id="bar3d_container" class="bar3d"></div>
			<div id="spider_container" class="spider"></div>
		</figure>

	<!-- Bias Chart Script -->
		<script src="https://code.highcharts.com/highcharts.js"></script>
		<script src="https://code.highcharts.com/highcharts-3d.js"></script>
		<script src="https://code.highcharts.com/highcharts-more.js"></script>
		<script src="{% static 'src/bias_chart.js' %}"></script>

	<!-- Resource Script -->
		<script>
			const bias_data = {
				value1: [
					{{result.ocm.statistical_parity_difference}},
					{{result.ocm.disparate_impact}},
					{{result.ocm.equal_opportunity_difference}},
					{{result.ocm.average_odds_difference}},
					{{result.ocm.theil_index}}
				],
				value2: [
					{{result.tcm.statistical_parity_difference}},
					{{result.tcm.disparate_impact}},
					{{result.tcm.equal_opportunity_difference}},
					{{result.tcm.average_odds_difference}},
					{{result.tcm.theil_index}}
				]
			}

			// Bar Bias_chart
			const bar = new BarChart('bar_container');
			bar.push(bias_data.value1, {color: "#FF0000bb", name: "original"});
			bar.push(bias_data.value2, {name: "mitigated"});
			bar.show();

			// 3D Bar Bias_chart
			const bar3d = new BarChart3D('bar3d_container');
			bar3d.push(bias_data.value1, {color: "#FF0000bb", name: "original"});
			bar3d.push(bias_data.value2, {name: "mitigated"});
			bar3d.show();

			// Spider Web Bias_chart
			const spider = new SpiderWebChart('spider_container');
			spider.push(bias_data.value1, {color: "#FF0000bb", name: "original"});
			spider.push(bias_data.value2, {name: "mitigated"});
			spider.show();
		</script>
	{% else %}
	<p>
		Processing...Please wait...<br>
		<a href="{% url 'new:fVAE_result' %}?id={{id}}">Refresh</a>
	</p>
	{% endif %}

</body>
</html>